motor_5:
  waypoint_0:
    time : 4
    point: -7000
  waypoint_1:
    time : 8
    point: 5000
  waypoint_2:
    time : 4
    point: 0
motor_6:
  waypoint_0:
    time : 2
    point : 500
  waypoint_1:
    time : 4
    point : 500
  waypoint_2:
    time : 4
    point : -500
  waypoint_3:
    time : 4
    point : -500
  waypoint_4:
    time : 2
    point: 0
motor_7: 
  waypoint_0: 
    time : 4
    point: 7000
  waypoint_1: 
    time : 8
    point: -5000
  waypoint_2: 
    time : 4
    point: 0
motor_8: 
  waypoint_0: 
    time : 2
    point: -500
  waypoint_1: 
    time : 4
    point: -500
  waypoint_2:
    time : 4
    point: 500
  waypoint_3: 
    time : 4
    point: 500
  waypoint_4:
    time : 2
    point: 0
