0:
  name : leftDown
  led : 11
1:
  name : leftUp
  led : 7
2:
  name : rightDown
  led : 11
3:
  name : rightUp
  led : 5
4:
  name : twoDown
  led : 3
5:
  name : twoUp
  led : 4
6:
  name : heart
  led : 9
7:
  name : normal
  led : 1